(part "ESH227M050AH1AA"
    (packageRef "CAPPRD500W60D1000H1350")
    (interface
        (port "1" (symbPinId 1) (portName "+") (portType INOUT))
        (port "2" (symbPinId 2) (portName "-") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "221")
    (property "Mouser_Part_Number" "80-ESH227M050AH1AA")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/KEMET/ESH227M050AH1AA?qs=w9hhVRgtvfmnb2YOvt619g%3D%3D")
    (property "Manufacturer_Name" "KEMET")
    (property "Manufacturer_Part_Number" "ESH227M050AH1AA")
    (property "Description" "Kemet 220uF Electrolytic Aluminium Electrolytic Capacitor 50V dc, Through Hole - ESH227M050AH1AA")
    (property "Datasheet_Link" "https://componentsearchengine.com/Datasheets/1/ESH227M050AH1AA.pdf")
    (property "symbolName1" "ESH227M050AH1AA")
)
