(part "SB160-E3_54"
    (packageRef "DIOAD1405W86L465D235")
    (interface
        (port "1" (symbPinId 1) (portName "K") (portType INOUT))
        (port "2" (symbPinId 2) (portName "A") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "221")
    (property "Mouser_Part_Number" "625-SB160-E3")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Vishay-General-Semiconductor/SB160-E3-54?qs=u91jd7aysvPQGAQKmVmbIA%3D%3D")
    (property "Manufacturer_Name" "Vishay")
    (property "Manufacturer_Part_Number" "SB160-E3/54")
    (property "Description" "Schottky Diodes & Rectifiers 60 Volt 1.0 Amp 50 Amp IFSM")
    (property "Datasheet_Link" "https://componentsearchengine.com/Datasheets/2/SB160-E3_54.pdf")
    (property "symbolName1" "SB160-E3_54")
)
