(part "IRFI4321PBF"
    (packageRef "TO254P483X1018X2095-3P")
    (interface
        (port "1" (symbPinId 1) (portName "G") (portType INOUT))
        (port "2" (symbPinId 2) (portName "D") (portType INOUT))
        (port "3" (symbPinId 3) (portName "S") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "37")
    (property "Mouser_Part_Number" "942-IRFI4321PBF")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Infineon-Technologies/IRFI4321PBF?qs=9%252BKlkBgLFf1U%252BCGUGLBmvA%3D%3D")
    (property "Manufacturer_Name" "Infineon")
    (property "Manufacturer_Part_Number" "IRFI4321PBF")
    (property "Description" "MOSFET MOSFT 150V 34A 16mOhm 73nC")
    (property "Datasheet_Link" "")
    (property "symbolName1" "IRFI4321PBF")
)
