(part "LM2574-5_0YN"
    (packageRef "DIP762W57P254L952H343Q8N")
    (interface
        (port "1" (symbPinId 1) (portName "FB") (portType INOUT))
        (port "2" (symbPinId 2) (portName "SIG_GND") (portType INOUT))
        (port "3" (symbPinId 3) (portName "ON/OFF") (portType INOUT))
        (port "4" (symbPinId 4) (portName "PWR_GND") (portType INOUT))
        (port "5" (symbPinId 5) (portName "VIN") (portType INOUT))
        (port "6" (symbPinId 6) (portName "NC_1") (portType INOUT))
        (port "7" (symbPinId 7) (portName "OUTPUT") (portType INOUT))
        (port "8" (symbPinId 8) (portName "NC_2") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "101")
    (property "Mouser_Part_Number" "998-LM2574-5.0YN")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Microchip-Technology-Micrel/LM2574-50YN?qs=kh6iOki%2FeLG8tRVzGWSPaw%3D%3D")
    (property "Manufacturer_Name" "Microchip")
    (property "Manufacturer_Part_Number" "LM2574-5.0YN")
    (property "Description" "Microchip LM2574-5.0YN, Step Down DC-DC Converter, 500mA, 8-Pin PDIP")
    (property "Datasheet_Link" "https://ww1.microchip.com/downloads/en/DeviceDoc/lm2574.pdf")
    (property "symbolName1" "LM2574-5_0YN")
)
