(part "7447471331"
    (packageRef "WE-TIS_111190")
    (interface
        (port "1" (symbPinId 1) (portName "1") (portType INOUT))
        (port "2" (symbPinId 2) (portName "2") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "33")
    (property "Mouser_Part_Number" "710-7447471331")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Wurth-Elektronik/7447471331?qs=VxkwJfKV0FSJeL%252B3Zn%2FUiQ%3D%3D")
    (property "Manufacturer_Name" "Wurth Elektronik")
    (property "Manufacturer_Part_Number" "7447471331")
    (property "Description" "Shielded Radial Leaded Inductor")
    (property "Datasheet_Link" "")
    (property "symbolName1" "7447471331")
)
